import Header from "@/components/Header/Header";
import "./globals.css";
import type { Metadata } from "next";
import Footer from "@/components/Footer";
import AppInitializer from "@/stores/AppInitializar";

export const metadata: Metadata = {
  title: " Next Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppInitializer>
          <Header />
          {children}
          <Footer />
        </AppInitializer>
      </body>
    </html>
  );
}
